import SEOHead from '../components/SEOHead'
import AdPlaceholder from '../components/AdPlaceholder'

export default function Disclaimer() {
  return (
    <>
      <SEOHead
        title="Disclaimer | RentReceiptIndia"
        description="Financial and tax disclaimer for RentReceiptIndia. This tool is for informational purposes only. Consult a CA for professional advice."
        path="/disclaimer"
      />

      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-primary mb-2">Disclaimer</h1>
        <p className="text-sm text-text-secondary mb-8">Last updated: January 1, 2025</p>

        <div className="prose prose-slate max-w-none space-y-5 text-text-secondary leading-relaxed">
          <h2 className="text-xl font-semibold text-primary mt-8 mb-3">General Disclaimer</h2>
          <p>
            The information provided by <strong>RentReceiptIndia</strong> on this website is for general
            informational and convenience purposes only. All information on the site is provided in
            good faith; however, we make <strong>no representation or warranty of any kind</strong>,
            express or implied, regarding the accuracy, adequacy, validity, reliability, availability,
            or completeness of any information on the site.
          </p>

          <h2 className="text-xl font-semibold text-primary mt-8 mb-3">Not Tax or Legal Advice</h2>
          <p>
            This website and its rent receipt generator tool are <strong>not a substitute for
            professional tax, legal, or financial advice</strong>. The content on this website,
            including blog posts, FAQs, and tool descriptions, is provided for educational and
            informational purposes only.
          </p>
          <p>
            Tax laws in India are complex and subject to change. What applies to one individual may
            not apply to another based on their specific circumstances. We strongly recommend that
            you <strong>consult a qualified Chartered Accountant (CA) or tax professional</strong>{' '}
            before making any decisions related to your tax filings, HRA claims, or financial planning.
          </p>

          <h2 className="text-xl font-semibold text-primary mt-8 mb-3">Receipt Accuracy</h2>
          <p>
            The rent receipts generated by our tool are <strong>templates</strong> based on the
            information you provide. We do not verify or validate any of the information you enter.
            It is your sole responsibility to ensure that:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>All details entered (names, PAN numbers, addresses, amounts) are accurate and truthful.</li>
            <li>The rent receipts reflect actual rent payments made by you.</li>
            <li>The receipts comply with the requirements of your employer and the Income Tax Department.</li>
            <li>You have a genuine rental arrangement with the landlord named in the receipts.</li>
          </ul>

          <h2 className="text-xl font-semibold text-primary mt-8 mb-3">Fraudulent Use Warning</h2>
          <p>
            We explicitly <strong>condemn and prohibit</strong> the use of this tool for generating
            false, fake, or fraudulent rent receipts. Creating fake rent receipts for the purpose of
            making false HRA claims is:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>A <strong>criminal offense</strong> under the Indian Penal Code (Section 420 — Cheating)</li>
            <li>Punishable under the <strong>Income Tax Act</strong> (Sections 270A and 277) with
              penalties ranging from 50% to 200% of tax on under-reported income, and imprisonment
              up to 7 years</li>
            <li>Grounds for <strong>prosecution and criminal proceedings</strong> by the Income Tax Department</li>
          </ul>
          <p>
            If the Income Tax Department discovers that your HRA claim is based on fraudulent receipts
            during assessment, scrutiny, or an audit, you may face severe penalties, interest on unpaid
            tax, and criminal prosecution. <strong>We bear no responsibility for any misuse of this tool.</strong>
          </p>

          <h2 className="text-xl font-semibold text-primary mt-8 mb-3">Limitation of Liability</h2>
          <p>
            Under no circumstances shall RentReceiptIndia, its creators, or its contributors be liable
            for any loss, damage, or expense arising from your use of this website or tool. This
            includes, without limitation:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Any tax penalties, notices, or assessments from the Income Tax Department</li>
            <li>Any errors in the generated receipts</li>
            <li>Any consequences arising from incorrect or false information entered by you</li>
            <li>Any financial losses or legal consequences of any kind</li>
          </ul>

          <h2 className="text-xl font-semibold text-primary mt-8 mb-3">External Links</h2>
          <p>
            This website may contain links to external websites that are not provided or maintained
            by us. We do not guarantee the accuracy, relevance, timeliness, or completeness of any
            information on these external websites.
          </p>

          <h2 className="text-xl font-semibold text-primary mt-8 mb-3">Contact</h2>
          <p>
            If you have questions or concerns about this disclaimer, please contact us at{' '}
            <a href="mailto:contact@rentreceiptindia.in" className="text-primary underline">
              contact@rentreceiptindia.in
            </a>.
          </p>
        </div>

        <AdPlaceholder slot="disclaimer-bottom" className="mt-8" />
      </div>
    </>
  )
}
